# Generated by Django 4.1.7 on 2023-03-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_img',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_icon',
            field=models.CharField(default='loader', max_length=10),
            preserve_default=False,
        ),
    ]
